# Generated by Django 3.1.4 on 2021-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionupdaterequest',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Only visible to staff and admins'),
        ),
    ]
