# Generated by Django 2.0 on 2018-02-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180210_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcaprofile',
            name='wca_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
