# Generated by Django 2.0 on 2018-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_pcaprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcaprofile',
            name='city_province',
            field=models.CharField(blank=True, choices=[('Caloocan', 'Caloocan'), ('Las Piñas', 'Las Piñas'), ('Makati', 'Makati'), ('Malabon', 'Malabon'), ('Mandaluyong', 'Mandaluyong'), ('City of Manila', 'City of Manila'), ('Marikina', 'Marikina'), ('Muntinlupa', 'Muntinlupa'), ('Navotas', 'Navotas'), ('Parañaque', 'Parañaque'), ('Pasay', 'Pasay'), ('Pasig', 'Pasig'), ('Pateros', 'Pateros'), ('Quezon City', 'Quezon City'), ('San Juan', 'San Juan'), ('Taguig', 'Taguig'), ('Valenzuela', 'Valenzuela'), ('Ilocos Norte', 'Ilocos Norte'), ('Ilocos Sur', 'Ilocos Sur'), ('La Union', 'La Union'), ('Pangasinan', 'Pangasinan'), ('Abra', 'Abra'), ('Apayao', 'Apayao'), ('Benguet', 'Benguet'), ('Ifugao', 'Ifugao'), ('Kalinga', 'Kalinga'), ('Mountain Province', 'Mountain Province'), ('Baguio', 'Baguio'), ('Batanes', 'Batanes'), ('Cagayan', 'Cagayan'), ('Isabela', 'Isabela'), ('Nueva Vizcaya', 'Nueva Vizcaya'), ('Quirino', 'Quirino'), ('Aurora', 'Aurora'), ('Bataan', 'Bataan'), ('Bulacan', 'Bulacan'), ('Nueva Ecija', 'Nueva Ecija'), ('Pampanga', 'Pampanga'), ('Tarlac', 'Tarlac'), ('Zambales', 'Zambales'), ('Angeles', 'Angeles'), ('Olongapo', 'Olongapo'), ('Batangas', 'Batangas'), ('Cavite', 'Cavite'), ('Laguna', 'Laguna'), ('Quezon', 'Quezon'), ('Rizal', 'Rizal'), ('Lucena', 'Lucena'), ('Marinduque', 'Marinduque'), ('Occidental Mindoro', 'Occidental Mindoro'), ('Oriental Mindoro', 'Oriental Mindoro'), ('Palawan', 'Palawan'), ('Romblon', 'Romblon'), ('Puerto Princesa', 'Puerto Princesa'), ('Albay', 'Albay'), ('Camarines Norte', 'Camarines Norte'), ('Camarines Sur', 'Camarines Sur'), ('Catanduanes', 'Catanduanes'), ('Masbate', 'Masbate'), ('Sorsogon', 'Sorsogon'), ('Aklan', 'Aklan'), ('Antique', 'Antique'), ('Capiz', 'Capiz'), ('Guimaras', 'Guimaras'), ('Iloilo', 'Iloilo'), ('Negros Occidental', 'Negros Occidental'), ('Bacolod City', 'Bacolod City'), ('Iloilo City', 'Iloilo City'), ('Bohol', 'Bohol'), ('Cebu', 'Cebu'), ('Negros Oriental', 'Negros Oriental'), ('Siquijor', 'Siquijor'), ('Cebu City', 'Cebu City'), ('Lapu-Lapu', 'Lapu-Lapu'), ('Mandaue', 'Mandaue'), ('Biliran', 'Biliran'), ('Eastern Samar', 'Eastern Samar'), ('Leyte', 'Leyte'), ('Northern Samar', 'Northern Samar'), ('Samar', 'Samar'), ('Southern Leyte', 'Southern Leyte'), ('Tacloban', 'Tacloban'), ('Zamboanga del Norte', 'Zamboanga del Norte'), ('Zamboanga del Sur', 'Zamboanga del Sur'), ('Zamboanga Sibugay', 'Zamboanga Sibugay'), ('Zamboanga City', 'Zamboanga City'), ('Isabela City', 'Isabela City'), ('Bukidnon', 'Bukidnon'), ('Camiguin', 'Camiguin'), ('Lanao del Norte', 'Lanao del Norte'), ('Misamis Occidental', 'Misamis Occidental'), ('Misamis Oriental', 'Misamis Oriental'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan', 'Iligan'), ('Compostela Valley', 'Compostela Valley'), ('Davao del Norte', 'Davao del Norte'), ('Davao del Sur', 'Davao del Sur'), ('Davao Occidental', 'Davao Occidental'), ('Davao Oriental', 'Davao Oriental'), ('Davao City', 'Davao City'), ('Cotabato', 'Cotabato'), ('Sarangani', 'Sarangani'), ('South Cotabato', 'South Cotabato'), ('Sultan Kudarat', 'Sultan Kudarat'), ('Cotabato City', 'Cotabato City'), ('General Santos', 'General Santos'), ('Agusan del Norte', 'Agusan del Norte'), ('Agusan del Sur', 'Agusan del Sur'), ('Dinagat Islands', 'Dinagat Islands'), ('Surigao del Norte', 'Surigao del Norte'), ('Surigao del Sur', 'Surigao del Sur'), ('Basilan', 'Basilan'), ('Lanao del Sur', 'Lanao del Sur'), ('Maguindanao', 'Maguindanao'), ('Sulu', 'Sulu'), ('Tawi-Tawi', 'Tawi-Tawi')], max_length=255, null=True, verbose_name='City/Province'),
        ),
        migrations.AlterField(
            model_name='pcaprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('NCR', 'National Capital Region'), ('Region I', 'Ilocos Region'), ('CAR', 'Cordillera Administrative Region'), ('Region II', 'Cagayan Valley'), ('Region III', 'Central Luzon'), ('Region IV-A', 'CALABARZON'), ('Region IV-B', 'MIMAROPA'), ('Region V', 'Bicol Region'), ('Region VI', 'Western Visayas'), ('Region VII', 'Central Visayas'), ('Region VIII', 'Eastern Visayas'), ('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('Region XIII', 'Caraga Region'), ('Region ARMM', 'Autonomous Region in Muslim Mindanao')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wcaprofile',
            name='delegate_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='wcaprofile',
            name='wca_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
