# Generated by Django 2.0 on 2018-03-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_databaseconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='inactive_database',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
