# Generated by Django 3.2 on 2021-04-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True),
        ),
    ]
