#!/usr/bin/env bash
echo "Syncing WCA database from the WCA export"
printf "Note: This script should be ran inside the docker container\n\n"

echo "Step 1: Downloading WCA Database"
curl https://www.worldcubeassociation.org/results/misc/WCA_export.sql.zip -o /app/data/WCA_export.sql.zip

echo "Step 2: Unzipping archive"
unzip /app/data/WCA_export.sql.zip -d /app/data/

echo "Step 3: Getting db config"
active_db="$(python /app/src/manage.py get_active_db)"

if [ "${active_db}" = "wca1" ]; then
    inactive_db="wca2"
else
    inactive_db="wca1"
fi

echo "Active DB: $active_db"
echo "Inactive DB: $inactive_db"

echo "Step 4: Importing WCA Database to $inactive_db using root user"
mysql -u root -p -h $MYSQL_HOST $inactive_db < /app/data/WCA_export.sql

echo "Step 5: Toggling $inactive_db as the active db"
output="$(python /app/src/manage.py toggle_active_db)"
echo "$output"
