# Generated by Django 2.0 on 2018-03-18 14:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('has_default_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_database', models.CharField(max_length=100)),
                ('inactive_database', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PCAProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('NCR', 'National Capital Region'), ('Region I', 'Ilocos Region'), ('CAR', 'Cordillera Administrative Region'), ('Region II', 'Cagayan Valley'), ('Region III', 'Central Luzon'), ('Region IV-A', 'CALABARZON'), ('Region IV-B', 'MIMAROPA'), ('Region V', 'Bicol Region'), ('Region VI', 'Western Visayas'), ('Region VII', 'Central Visayas'), ('Region VIII', 'Eastern Visayas'), ('Region IX', 'Zamboanga Peninsula'), ('Region X', 'Northern Mindanao'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKSARGEN'), ('Region XIII', 'Caraga Region'), ('ARMM', 'Autonomous Region in Muslim Mindanao')], max_length=255, null=True)),
                ('city_province', models.CharField(blank=True, choices=[('Caloocan', 'Caloocan'), ('Las Piñas', 'Las Piñas'), ('Makati', 'Makati'), ('Malabon', 'Malabon'), ('Mandaluyong', 'Mandaluyong'), ('City of Manila', 'City of Manila'), ('Marikina', 'Marikina'), ('Muntinlupa', 'Muntinlupa'), ('Navotas', 'Navotas'), ('Parañaque', 'Parañaque'), ('Pasay', 'Pasay'), ('Pasig', 'Pasig'), ('Pateros', 'Pateros'), ('Quezon City', 'Quezon City'), ('San Juan', 'San Juan'), ('Taguig', 'Taguig'), ('Valenzuela', 'Valenzuela'), ('Ilocos Norte', 'Ilocos Norte'), ('Ilocos Sur', 'Ilocos Sur'), ('La Union', 'La Union'), ('Pangasinan', 'Pangasinan'), ('Abra', 'Abra'), ('Apayao', 'Apayao'), ('Benguet', 'Benguet'), ('Ifugao', 'Ifugao'), ('Kalinga', 'Kalinga'), ('Mountain Province', 'Mountain Province'), ('Baguio', 'Baguio'), ('Batanes', 'Batanes'), ('Cagayan', 'Cagayan'), ('Isabela', 'Isabela'), ('Nueva Vizcaya', 'Nueva Vizcaya'), ('Quirino', 'Quirino'), ('Aurora', 'Aurora'), ('Bataan', 'Bataan'), ('Bulacan', 'Bulacan'), ('Nueva Ecija', 'Nueva Ecija'), ('Pampanga', 'Pampanga'), ('Tarlac', 'Tarlac'), ('Zambales', 'Zambales'), ('Angeles', 'Angeles'), ('Olongapo', 'Olongapo'), ('Batangas', 'Batangas'), ('Cavite', 'Cavite'), ('Laguna', 'Laguna'), ('Quezon', 'Quezon'), ('Rizal', 'Rizal'), ('Lucena', 'Lucena'), ('Marinduque', 'Marinduque'), ('Occidental Mindoro', 'Occidental Mindoro'), ('Oriental Mindoro', 'Oriental Mindoro'), ('Palawan', 'Palawan'), ('Romblon', 'Romblon'), ('Puerto Princesa', 'Puerto Princesa'), ('Albay', 'Albay'), ('Camarines Norte', 'Camarines Norte'), ('Camarines Sur', 'Camarines Sur'), ('Catanduanes', 'Catanduanes'), ('Masbate', 'Masbate'), ('Sorsogon', 'Sorsogon'), ('Aklan', 'Aklan'), ('Antique', 'Antique'), ('Capiz', 'Capiz'), ('Guimaras', 'Guimaras'), ('Iloilo', 'Iloilo'), ('Negros Occidental', 'Negros Occidental'), ('Bacolod City', 'Bacolod City'), ('Iloilo City', 'Iloilo City'), ('Bohol', 'Bohol'), ('Cebu', 'Cebu'), ('Negros Oriental', 'Negros Oriental'), ('Siquijor', 'Siquijor'), ('Cebu City', 'Cebu City'), ('Lapu-Lapu', 'Lapu-Lapu'), ('Mandaue', 'Mandaue'), ('Biliran', 'Biliran'), ('Eastern Samar', 'Eastern Samar'), ('Leyte', 'Leyte'), ('Northern Samar', 'Northern Samar'), ('Samar', 'Samar'), ('Southern Leyte', 'Southern Leyte'), ('Tacloban', 'Tacloban'), ('Zamboanga del Norte', 'Zamboanga del Norte'), ('Zamboanga del Sur', 'Zamboanga del Sur'), ('Zamboanga Sibugay', 'Zamboanga Sibugay'), ('Zamboanga City', 'Zamboanga City'), ('Isabela City', 'Isabela City'), ('Bukidnon', 'Bukidnon'), ('Camiguin', 'Camiguin'), ('Lanao del Norte', 'Lanao del Norte'), ('Misamis Occidental', 'Misamis Occidental'), ('Misamis Oriental', 'Misamis Oriental'), ('Cagayan de Oro', 'Cagayan de Oro'), ('Iligan', 'Iligan'), ('Compostela Valley', 'Compostela Valley'), ('Davao del Norte', 'Davao del Norte'), ('Davao del Sur', 'Davao del Sur'), ('Davao Occidental', 'Davao Occidental'), ('Davao Oriental', 'Davao Oriental'), ('Davao City', 'Davao City'), ('Cotabato', 'Cotabato'), ('Sarangani', 'Sarangani'), ('South Cotabato', 'South Cotabato'), ('Sultan Kudarat', 'Sultan Kudarat'), ('Cotabato City', 'Cotabato City'), ('General Santos', 'General Santos'), ('Agusan del Norte', 'Agusan del Norte'), ('Agusan del Sur', 'Agusan del Sur'), ('Dinagat Islands', 'Dinagat Islands'), ('Surigao del Norte', 'Surigao del Norte'), ('Surigao del Sur', 'Surigao del Sur'), ('Basilan', 'Basilan'), ('Lanao del Sur', 'Lanao del Sur'), ('Maguindanao', 'Maguindanao'), ('Sulu', 'Sulu'), ('Tawi-Tawi', 'Tawi-Tawi')], max_length=255, null=True, verbose_name='City/Province')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WCAProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wca_pk', models.IntegerField()),
                ('wca_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=10)),
                ('country_iso2', models.CharField(max_length=10)),
                ('delegate_status', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar_url', models.CharField(max_length=255)),
                ('avatar_thumb_url', models.CharField(max_length=255)),
                ('is_default_avatar', models.BooleanField()),
                ('wca_created_at', models.CharField(max_length=500)),
                ('wca_updated_at', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
