REGIONS = (
    ('NCR', 'National Capital Region'),
    ('Region I', 'Ilocos Region'),
    ('CAR', 'Cordillera Administrative Region'),
    ('Region II', 'Cagayan Valley'),
    ('Region III', 'Central Luzon'),
    ('Region IV-A', 'CALABARZON'),
    ('Region IV-B', 'MIMAROPA'),
    ('Region V', 'Bicol Region'),
    ('Region VI', 'Western Visayas'),
    ('Region VII', 'Central Visayas'),
    ('Region VIII', 'Eastern Visayas'),
    ('Region IX', 'Zamboanga Peninsula'),
    ('Region X', 'Northern Mindanao'),
    ('Region XI', 'Davao Region'),
    ('Region XII', 'SOCCSKSARGEN'),
    ('Region XIII', 'Caraga Region'),
    ('Region ARMM', 'Autonomous Region in Muslim Mindanao'),
)

CITIES_PROVINCES = (
    # NCR
    ('Caloocan', 'Caloocan'),
    ('Las Piñas', 'Las Piñas'),
    ('Makati', 'Makati'),
    ('Malabon', 'Malabon'),
    ('Mandaluyong', 'Mandaluyong'),
    ('City of Manila', 'City of Manila'),
    ('Marikina', 'Marikina'),
    ('Muntinlupa', 'Muntinlupa'),
    ('Navotas', 'Navotas'),
    ('Parañaque', 'Parañaque'),
    ('Pasay', 'Pasay'),
    ('Pasig', 'Pasig'),
    ('Pateros', 'Pateros'),
    ('Quezon City', 'Quezon City'),
    ('San Juan', 'San Juan'),
    ('Taguig', 'Taguig'),
    ('Valenzuela', 'Valenzuela'),
    # Region I
    ('Ilocos Norte', 'Ilocos Norte'),
    ('Ilocos Sur', 'Ilocos Sur'),
    ('La Union', 'La Union'),
    ('Pangasinan', 'Pangasinan'),
    # CAR
    ('Abra', 'Abra'),
    ('Apayao', 'Apayao'),
    ('Benguet', 'Benguet'),
    ('Ifugao', 'Ifugao'),
    ('Kalinga', 'Kalinga'),
    ('Mountain Province', 'Mountain Province'),
    ('Baguio', 'Baguio'),
    # Region II
    ('Batanes', 'Batanes'),
    ('Cagayan', 'Cagayan'),
    ('Isabela', 'Isabela'),
    ('Nueva Vizcaya', 'Nueva Vizcaya'),
    ('Quirino', 'Quirino'),
    # Region III
    ('Aurora', 'Aurora'),
    ('Bataan', 'Bataan'),
    ('Bulacan', 'Bulacan'),
    ('Nueva Ecija', 'Nueva Ecija'),
    ('Pampanga', 'Pampanga'),
    ('Tarlac', 'Tarlac'),
    ('Zambales', 'Zambales'),
    ('Angeles', 'Angeles'),
    ('Olongapo', 'Olongapo'),
    # Region IV-A
    ('Batangas', 'Batangas'),
    ('Cavite', 'Cavite'),
    ('Laguna', 'Laguna'),
    ('Quezon', 'Quezon'),
    ('Rizal', 'Rizal'),
    ('Lucena', 'Lucena'),
    # Region IV-B
    ('Marinduque', 'Marinduque'),
    ('Occidental Mindoro', 'Occidental Mindoro'),
    ('Oriental Mindoro', 'Oriental Mindoro'),
    ('Palawan', 'Palawan'),
    ('Romblon', 'Romblon'),
    ('Puerto Princesa', 'Puerto Princesa'),
    # Region V
    ('Albay', 'Albay'),
    ('Camarines Norte', 'Camarines Norte'),
    ('Camarines Sur', 'Camarines Sur'),
    ('Catanduanes', 'Catanduanes'),
    ('Masbate', 'Masbate'),
    ('Sorsogon', 'Sorsogon'),
    # Region VI
    ('Aklan', 'Aklan'),
    ('Antique', 'Antique'),
    ('Capiz', 'Capiz'),
    ('Guimaras', 'Guimaras'),
    ('Iloilo', 'Iloilo'),
    ('Negros Occidental', 'Negros Occidental'),
    ('Bacolod City', 'Bacolod City'),
    ('Iloilo City', 'Iloilo City'),
    # Region VII
    ('Bohol', 'Bohol'),
    ('Cebu', 'Cebu'),
    ('Negros Oriental', 'Negros Oriental'),
    ('Siquijor', 'Siquijor'),
    ('Cebu City', 'Cebu City'),
    ('Lapu-Lapu', 'Lapu-Lapu'),
    ('Mandaue', 'Mandaue'),
    # Region VIII
    ('Biliran', 'Biliran'),
    ('Eastern Samar', 'Eastern Samar'),
    ('Leyte', 'Leyte'),
    ('Northern Samar', 'Northern Samar'),
    ('Samar', 'Samar'),
    ('Southern Leyte', 'Southern Leyte'),
    ('Tacloban', 'Tacloban'),
    # Region IX
    ('Zamboanga del Norte', 'Zamboanga del Norte'),
    ('Zamboanga del Sur', 'Zamboanga del Sur'),
    ('Zamboanga Sibugay', 'Zamboanga Sibugay'),
    ('Zamboanga City', 'Zamboanga City'),
    ('Isabela City', 'Isabela City'),
    # Region X
    ('Bukidnon', 'Bukidnon'),
    ('Camiguin', 'Camiguin'),
    ('Lanao del Norte', 'Lanao del Norte'),
    ('Misamis Occidental', 'Misamis Occidental'),
    ('Misamis Oriental', 'Misamis Oriental'),
    ('Cagayan de Oro', 'Cagayan de Oro'),
    ('Iligan', 'Iligan'),
    # Region XI
    ('Compostela Valley', 'Compostela Valley'),
    ('Davao del Norte', 'Davao del Norte'),
    ('Davao del Sur', 'Davao del Sur'),
    ('Davao Occidental', 'Davao Occidental'),
    ('Davao Oriental', 'Davao Oriental'),
    ('Davao City', 'Davao City'),
    # Region XII
    ('Cotabato', 'Cotabato'),
    ('Sarangani', 'Sarangani'),
    ('South Cotabato', 'South Cotabato'),
    ('Sultan Kudarat', 'Sultan Kudarat'),
    ('Cotabato City', 'Cotabato City'),
    ('General Santos', 'General Santos'),
    # Region XIII
    ('Agusan del Norte', 'Agusan del Norte'),
    ('Agusan del Sur', 'Agusan del Sur'),
    ('Dinagat Islands', 'Dinagat Islands'),
    ('Surigao del Norte', 'Surigao del Norte'),
    ('Surigao del Sur', 'Surigao del Sur'),
    # Region ARMM
    ('Basilan', 'Basilan'),
    ('Lanao del Sur', 'Lanao del Sur'),
    ('Maguindanao', 'Maguindanao'),
    ('Sulu', 'Sulu'),
    ('Tawi-Tawi', 'Tawi-Tawi'),
)

CITIES_PROVINCES_DIRECTORY = {
    'NCR': [
        ['Caloocan', 'Caloocan'],
        ['Las Piñas', 'Las Piñas'],
        ['Makati', 'Makati'],
        ['Malabon', 'Malabon'],
        ['Mandaluyong', 'Mandaluyong'],
        ['City of Manila', 'City of Manila'],
        ['Marikina', 'Marikina'],
        ['Muntinlupa', 'Muntinlupa'],
        ['Navotas', 'Navotas'],
        ['Parañaque', 'Parañaque'],
        ['Pasay', 'Pasay'],
        ['Pasig', 'Pasig'],
        ['Pateros', 'Pateros'],
        ['Quezon City', 'Quezon City'],
        ['San Juan', 'San Juan'],
        ['Taguig', 'Taguig'],
        ['Valenzuela', 'Valenzuela'],
    ],
    'Region I': [
        ['Ilocos Norte', 'Ilocos Norte'],
        ['Ilocos Sur', 'Ilocos Sur'],
        ['La Union', 'La Union'],
        ['Pangasinan', 'Pangasinan'],
    ],
    'CAR': [
        ['Abra', 'Abra'],
        ['Apayao', 'Apayao'],
        ['Benguet', 'Benguet'],
        ['Ifugao', 'Ifugao'],
        ['Kalinga', 'Kalinga'],
        ['Mountain Province', 'Mountain Province'],
        ['Baguio', 'Baguio'],
    ],
    'Region II': [
        ['Batanes', 'Batanes'],
        ['Cagayan', 'Cagayan'],
        ['Isabela', 'Isabela'],
        ['Nueva Vizcaya', 'Nueva Vizcaya'],
        ['Quirino', 'Quirino'],
    ],
    'Region III': [
        ['Aurora', 'Aurora'],
        ['Bataan', 'Bataan'],
        ['Bulacan', 'Bulacan'],
        ['Nueva Ecija', 'Nueva Ecija'],
        ['Pampanga', 'Pampanga'],
        ['Tarlac', 'Tarlac'],
        ['Zambales', 'Zambales'],
        ['Angeles', 'Angeles'],
        ['Olongapo', 'Olongapo'],
    ],
    'Region IV-A': [
        ['Batangas', 'Batangas'],
        ['Cavite', 'Cavite'],
        ['Laguna', 'Laguna'],
        ['Quezon', 'Quezon'],
        ['Rizal', 'Rizal'],
        ['Lucena', 'Lucena'],
    ],
    'Region IV-B': [
        ['Marinduque', 'Marinduque'],
        ['Occidental Mindoro', 'Occidental Mindoro'],
        ['Oriental Mindoro', 'Oriental Mindoro'],
        ['Palawan', 'Palawan'],
        ['Romblon', 'Romblon'],
        ['Puerto Princesa', 'Puerto Princesa'],
    ],
    'Region V': [
        ['Albay', 'Albay'],
        ['Camarines Norte', 'Camarines Norte'],
        ['Camarines Sur', 'Camarines Sur'],
        ['Catanduanes', 'Catanduanes'],
        ['Masbate', 'Masbate'],
        ['Sorsogon', 'Sorsogon'],
    ],
    'Region VI': [
        ['Aklan', 'Aklan'],
        ['Antique', 'Antique'],
        ['Capiz', 'Capiz'],
        ['Guimaras', 'Guimaras'],
        ['Iloilo', 'Iloilo'],
        ['Negros Occidental', 'Negros Occidental'],
        ['Bacolod City', 'Bacolod City'],
        ['Iloilo City', 'Iloilo City'],
    ],
    'Region VII': [
        ['Bohol', 'Bohol'],
        ['Cebu', 'Cebu'],
        ['Negros Oriental', 'Negros Oriental'],
        ['Siquijor', 'Siquijor'],
        ['Cebu City', 'Cebu City'],
        ['Lapu-Lapu', 'Lapu-Lapu'],
        ['Mandaue', 'Mandaue'],
    ],
    'Region VIII': [
        ['Biliran', 'Biliran'],
        ['Eastern Samar', 'Eastern Samar'],
        ['Leyte', 'Leyte'],
        ['Northern Samar', 'Northern Samar'],
        ['Samar', 'Samar'],
        ['Southern Leyte', 'Southern Leyte'],
        ['Tacloban', 'Tacloban'],
    ],
    'Region IX': [
        ['Zamboanga del Norte', 'Zamboanga del Norte'],
        ['Zamboanga del Sur', 'Zamboanga del Sur'],
        ['Zamboanga Sibugay', 'Zamboanga Sibugay'],
        ['Zamboanga City', 'Zamboanga City'],
        ['Isabela City', 'Isabela City'],
    ],
    'Region X': [
        ['Bukidnon', 'Bukidnon'],
        ['Camiguin', 'Camiguin'],
        ['Lanao del Norte', 'Lanao del Norte'],
        ['Misamis Occidental', 'Misamis Occidental'],
        ['Misamis Oriental', 'Misamis Oriental'],
        ['Cagayan de Oro', 'Cagayan de Oro'],
        ['Iligan', 'Iligan'],
    ],
    'Region XI': [
        ['Compostela Valley', 'Compostela Valley'],
        ['Davao del Norte', 'Davao del Norte'],
        ['Davao del Sur', 'Davao del Sur'],
        ['Davao Occidental', 'Davao Occidental'],
        ['Davao Oriental', 'Davao Oriental'],
        ['Davao City', 'Davao City'],
    ],
    'Region XII': [
        ['Cotabato', 'Cotabato'],
        ['Sarangani', 'Sarangani'],
        ['South Cotabato', 'South Cotabato'],
        ['Sultan Kudarat', 'Sultan Kudarat'],
        ['Cotabato City', 'Cotabato City'],
        ['General Santos', 'General Santos'],
    ],
    'Region XIII': [
        ['Agusan del Norte', 'Agusan del Norte'],
        ['Agusan del Sur', 'Agusan del Sur'],
        ['Dinagat Islands', 'Dinagat Islands'],
        ['Surigao del Norte', 'Surigao del Norte'],
        ['Surigao del Sur', 'Surigao del Sur'],
    ],
    'Region ARMM': [
        ['Basilan', 'Basilan'],
        ['Lanao del Sur', 'Lanao del Sur'],
        ['Maguindanao', 'Maguindanao'],
        ['Sulu', 'Sulu'],
        ['Tawi-Tawi', 'Tawi-Tawi'],
    ],
}
